<?php

return array (
  0 => 
  array (
    'id' => 1,
    'name' => 'Hà Nội',
    'slug' => 'ha-noi',
    'type' => 'Trung ương',
    'lat' => '21.0283334',
    'lon' => '105.854041',
    'region' => 'Đồng bằng sông Hồng',
    'search_name' => 'Hanoi',
  ),
  1 => 
  array (
    'id' => 2,
    'name' => 'Hà Giang',
    'slug' => 'ha-giang',
    'type' => 'Tỉnh',
    'lat' => '22.7336097',
    'lon' => '105.0027271',
    'region' => 'Đông Bắc Bộ',
    'search_name' => 'Ha Giang',
  ),
  2 => 
  array (
    'id' => 4,
    'name' => 'Cao Bằng',
    'slug' => 'cao-bang',
    'type' => 'Tỉnh',
    'lat' => '22.7426936',
    'lon' => '106.1060926',
    'region' => 'Đông Bắc Bộ',
    'search_name' => 'Cao Bang',
  ),
  3 => 
  array (
    'id' => 6,
    'name' => 'Bắc Kạn',
    'slug' => 'bac-kan',
    'type' => 'Tỉnh',
    'lat' => '22.2571701',
    'lon' => '105.8204437',
    'region' => 'Đông Bắc Bộ',
    'search_name' => 'Bac Kan',
  ),
  4 => 
  array (
    'id' => 8,
    'name' => 'Tuyên Quang',
    'slug' => 'tuyen-quang',
    'type' => 'Tỉnh',
    'lat' => '22.0747798',
    'lon' => '105.258411',
    'region' => 'Tây Bắc Bộ',
    'search_name' => 'Tuyen Quang',
  ),
  5 => 
  array (
    'id' => 10,
    'name' => 'Lào Cai',
    'slug' => 'lao-cai',
    'type' => 'Tỉnh',
    'lat' => '22.3069302',
    'lon' => '104.1829592',
    'region' => 'Tây Bắc Bộ',
    'search_name' => 'Lao Cai',
  ),
  6 => 
  array (
    'id' => 11,
    'name' => 'Điện Biên',
    'slug' => 'dien-bien',
    'type' => 'Tỉnh',
    'lat' => '21.6546566',
    'lon' => '103.2168632',
    'region' => 'Tây Bắc Bộ',
    'search_name' => 'Dien Bien',
  ),
  7 => 
  array (
    'id' => 12,
    'name' => 'Lai Châu',
    'slug' => 'lai-chau',
    'type' => 'Tỉnh',
    'lat' => '22.2921668',
    'lon' => '103.1798662',
    'region' => 'Tây Bắc Bộ',
    'search_name' => 'Lai Chau',
  ),
  8 => 
  array (
    'id' => 14,
    'name' => 'Sơn La',
    'slug' => 'son-la',
    'type' => 'Tỉnh',
    'lat' => '21.2276769',
    'lon' => '104.1575944',
    'region' => 'Tây Bắc Bộ',
    'search_name' => 'Son La',
  ),
  9 => 
  array (
    'id' => 15,
    'name' => 'Yên Bái',
    'slug' => 'yen-bai',
    'type' => 'Tỉnh',
    'lat' => '21.69611',
    'lon' => '104.8752392',
    'region' => 'Tây Bắc Bộ',
    'search_name' => 'Yen Bai',
  ),
  10 => 
  array (
    'id' => 17,
    'name' => 'Hoà Bình',
    'slug' => 'hoa-binh',
    'type' => 'Tỉnh',
    'lat' => '20.6763365',
    'lon' => '105.3759952',
    'region' => 'Đông Bắc Bộ',
    'search_name' => 'Hoa Binh',
  ),
  11 => 
  array (
    'id' => 19,
    'name' => 'Thái Nguyên',
    'slug' => 'thai-nguyen',
    'type' => 'Tỉnh',
    'lat' => '21.592477',
    'lon' => '105.8435398',
    'region' => 'Đông Bắc Bộ',
    'search_name' => 'Thai Nguyen',
  ),
  12 => 
  array (
    'id' => 20,
    'name' => 'Lạng Sơn',
    'slug' => 'lang-son',
    'type' => 'Tỉnh',
    'lat' => '21.7773599',
    'lon' => '106.740412',
    'region' => 'Đông Bắc Bộ',
    'search_name' => 'Lang Son',
  ),
  13 => 
  array (
    'id' => 22,
    'name' => 'Quảng Ninh',
    'slug' => 'quang-ninh',
    'type' => 'Tỉnh',
    'lat' => '21.1718046',
    'lon' => '107.2012742',
    'region' => 'Đông Bắc Bộ',
    'search_name' => 'Ha Long',
  ),
  14 => 
  array (
    'id' => 24,
    'name' => 'Bắc Giang',
    'slug' => 'bac-giang',
    'type' => 'Tỉnh',
    'lat' => '21.3169625',
    'lon' => '106.437985',
    'region' => 'Đông Bắc Bộ',
    'search_name' => 'Bac Giang',
  ),
  15 => 
  array (
    'id' => 25,
    'name' => 'Phú Thọ',
    'slug' => 'phu-tho',
    'type' => 'Tỉnh',
    'lat' => '21.3007538',
    'lon' => '105.1349604',
    'region' => 'Đông Bắc Bộ',
    'search_name' => 'Phu Tho',
  ),
  16 => 
  array (
    'id' => 26,
    'name' => 'Vĩnh Phúc',
    'slug' => 'vinh-phuc',
    'type' => 'Tỉnh',
    'lat' => '21.3778689',
    'lon' => '105.5758286',
    'region' => 'Đồng bằng sông Hồng',
    'search_name' => 'Vinh Phuc',
  ),
  17 => 
  array (
    'id' => 27,
    'name' => 'Bắc Ninh',
    'slug' => 'bac-ninh',
    'type' => 'Tỉnh',
    'lat' => '21.0955822',
    'lon' => '106.1264766',
    'region' => 'Đồng bằng sông Hồng',
    'search_name' => 'Bac Ninh',
  ),
  18 => 
  array (
    'id' => 30,
    'name' => 'Hải Dương',
    'slug' => 'hai-duong',
    'type' => 'Tỉnh',
    'lat' => '20.8930571',
    'lon' => '106.3725441',
    'region' => 'Đồng bằng sông Hồng',
    'search_name' => 'Hai Duong',
  ),
  19 => 
  array (
    'id' => 31,
    'name' => 'Hải Phòng',
    'slug' => 'hai-phong',
    'type' => 'Trung ương',
    'lat' => '20.858864',
    'lon' => '106.6749591',
    'region' => 'Đồng bằng sông Hồng',
    'search_name' => 'Hai Phong',
  ),
  20 => 
  array (
    'id' => 33,
    'name' => 'Hưng Yên',
    'slug' => 'hung-yen',
    'type' => 'Tỉnh',
    'lat' => '20.7833912',
    'lon' => '106.0699025',
    'region' => 'Đồng bằng sông Hồng',
    'search_name' => 'Hung Yen',
  ),
  21 => 
  array (
    'id' => 34,
    'name' => 'Thái Bình',
    'slug' => 'thai-binh',
    'type' => 'Tỉnh',
    'lat' => '20.5296832',
    'lon' => '106.3876068',
    'region' => 'Đồng bằng sông Hồng',
    'search_name' => 'Thai Binh',
  ),
  22 => 
  array (
    'id' => 35,
    'name' => 'Hà Nam',
    'slug' => 'ha-nam',
    'type' => 'Tỉnh',
    'lat' => '20.532909',
    'lon' => '105.976318',
    'region' => 'Đồng bằng sông Hồng',
    'search_name' => 'Ha Nam',
  ),
  23 => 
  array (
    'id' => 36,
    'name' => 'Nam Định',
    'slug' => 'nam-dinh',
    'type' => 'Tỉnh',
    'lat' => '20.2686476',
    'lon' => '106.2289075',
    'region' => 'Đồng bằng sông Hồng',
    'search_name' => 'Nam Dinh',
  ),
  24 => 
  array (
    'id' => 37,
    'name' => 'Ninh Bình',
    'slug' => 'ninh-binh',
    'type' => 'Tỉnh',
    'lat' => '20.2545421',
    'lon' => '105.9764854',
    'region' => 'Đồng bằng sông Hồng',
    'search_name' => 'Ninh Binh',
  ),
  25 => 
  array (
    'id' => 38,
    'name' => 'Thanh Hóa',
    'slug' => 'thanh-hoa',
    'type' => 'Tỉnh',
    'lat' => '19.9781573',
    'lon' => '105.4816107',
    'region' => 'Bắc Trung Bộ',
    'search_name' => 'Thanh Hoa',
  ),
  26 => 
  array (
    'id' => 40,
    'name' => 'Nghệ An',
    'slug' => 'nghe-an',
    'type' => 'Tỉnh',
    'lat' => '19.1976001',
    'lon' => '105.060676',
    'region' => 'Bắc Trung Bộ',
    'search_name' => 'Vinh',
  ),
  27 => 
  array (
    'id' => 42,
    'name' => 'Hà Tĩnh',
    'slug' => 'ha-tinh',
    'type' => 'Tỉnh',
    'lat' => '18.3504832',
    'lon' => '105.7623047',
    'region' => 'Bắc Trung Bộ',
    'search_name' => 'Ha Tinh',
  ),
  28 => 
  array (
    'id' => 44,
    'name' => 'Quảng Bình',
    'slug' => 'quang-binh',
    'type' => 'Tỉnh',
    'lat' => '17.509599',
    'lon' => '106.4004452',
    'region' => 'Bắc Trung Bộ',
    'search_name' => 'Quang Binh',
  ),
  29 => 
  array (
    'id' => 45,
    'name' => 'Quảng Trị',
    'slug' => 'quang-tri',
    'type' => 'Tỉnh',
    'lat' => '16.7897806',
    'lon' => '106.9797431',
    'region' => 'Bắc Trung Bộ',
    'search_name' => 'Quang Tri',
  ),
  30 => 
  array (
    'id' => 46,
    'name' => 'Thừa Thiên Huế',
    'slug' => 'thua-thien-hue',
    'type' => 'Tỉnh',
    'lat' => '16.3480798',
    'lon' => '107.5398913',
    'region' => 'Bắc Trung Bộ',
    'search_name' => 'Hue',
  ),
  31 => 
  array (
    'id' => 48,
    'name' => 'Đà Nẵng',
    'slug' => 'da-nang',
    'type' => 'Trung ương',
    'lat' => '16.068',
    'lon' => '108.212',
    'region' => 'Nam Trung Bộ',
    'search_name' => 'Da Nang',
  ),
  32 => 
  array (
    'id' => 49,
    'name' => 'Quảng Nam',
    'slug' => 'quang-nam',
    'type' => 'Tỉnh',
    'lat' => '15.5761698',
    'lon' => '108.0527132',
    'region' => 'Nam Trung Bộ',
    'search_name' => 'Hoi An',
  ),
  33 => 
  array (
    'id' => 51,
    'name' => 'Quảng Ngãi',
    'slug' => 'quang-ngai',
    'type' => 'Tỉnh',
    'lat' => '14.9953739',
    'lon' => '108.691729',
    'region' => 'Nam Trung Bộ',
    'search_name' => 'Quang Ngai',
  ),
  34 => 
  array (
    'id' => 52,
    'name' => 'Bình Định',
    'slug' => 'binh-dinh',
    'type' => 'Tỉnh',
    'lat' => '14.0779378',
    'lon' => '108.9898798',
    'region' => 'Nam Trung Bộ',
    'search_name' => 'Binh Dinh',
  ),
  35 => 
  array (
    'id' => 54,
    'name' => 'Phú Yên',
    'slug' => 'phu-yen',
    'type' => 'Tỉnh',
    'lat' => '13.1912633',
    'lon' => '109.1273678',
    'region' => 'Nam Trung Bộ',
    'search_name' => 'Tuy Hoa',
  ),
  36 => 
  array (
    'id' => 56,
    'name' => 'Khánh Hòa',
    'slug' => 'khanh-hoa',
    'type' => 'Tỉnh',
    'lat' => '12.2980751',
    'lon' => '108.9950386',
    'region' => 'Nam Trung Bộ',
    'search_name' => 'Khanh Hoa',
  ),
  37 => 
  array (
    'id' => 58,
    'name' => 'Ninh Thuận',
    'slug' => 'ninh-thuan',
    'type' => 'Tỉnh',
    'lat' => '11.6965639',
    'lon' => '108.8928476',
    'region' => 'Nam Trung Bộ',
    'search_name' => 'Ninh Thuan',
  ),
  38 => 
  array (
    'id' => 60,
    'name' => 'Bình Thuận',
    'slug' => 'binh-thuan',
    'type' => 'Tỉnh',
    'lat' => '11.1041572',
    'lon' => '108.1832931',
    'region' => 'Nam Trung Bộ',
    'search_name' => 'Binh Thuan',
  ),
  39 => 
  array (
    'id' => 62,
    'name' => 'Kon Tum',
    'slug' => 'kon-tum',
    'type' => 'Tỉnh',
    'lat' => '14.6995372',
    'lon' => '107.9323831',
    'region' => 'Tây Nguyên',
    'search_name' => 'Kon Tum',
  ),
  40 => 
  array (
    'id' => 64,
    'name' => 'Gia Lai',
    'slug' => 'gia-lai',
    'type' => 'Tỉnh',
    'lat' => '13.8177445',
    'lon' => '108.2004015',
    'region' => 'Tây Nguyên',
    'search_name' => 'Gia Lai',
  ),
  41 => 
  array (
    'id' => 66,
    'name' => 'Đắk Lắk',
    'slug' => 'dak-lak',
    'type' => 'Tỉnh',
    'lat' => '12.8292274',
    'lon' => '108.2999058',
    'region' => 'Tây Nguyên',
    'search_name' => 'Buon Ma Thuot',
  ),
  42 => 
  array (
    'id' => 67,
    'name' => 'Đắk Nông',
    'slug' => 'dak-nong',
    'type' => 'Tỉnh',
    'lat' => '12.2818851',
    'lon' => '107.7302484',
    'region' => 'Tây Nguyên',
    'search_name' => 'Dak Nong',
  ),
  43 => 
  array (
    'id' => 68,
    'name' => 'Lâm Đồng',
    'slug' => 'lam-dong',
    'type' => 'Tỉnh',
    'lat' => '11.6614957',
    'lon' => '108.1335279',
    'region' => 'Tây Nguyên',
    'search_name' => 'Da Lat',
  ),
  44 => 
  array (
    'id' => 70,
    'name' => 'Bình Phước',
    'slug' => 'binh-phuoc',
    'type' => 'Tỉnh',
    'lat' => '11.7543232',
    'lon' => '106.9266473',
    'region' => 'Đông Nam Bộ',
    'search_name' => ' Phuoc Long',
  ),
  45 => 
  array (
    'id' => 72,
    'name' => 'Tây Ninh',
    'slug' => 'tay-ninh',
    'type' => 'Tỉnh',
    'lat' => '11.4019366',
    'lon' => '106.1626927',
    'region' => 'Đông Nam Bộ',
    'search_name' => 'Tay Ninh',
  ),
  46 => 
  array (
    'id' => 74,
    'name' => 'Bình Dương',
    'slug' => 'binh-duong',
    'type' => 'Tỉnh',
    'lat' => '11.1836551',
    'lon' => '106.7031737',
    'region' => 'Đông Nam Bộ',
    'search_name' => 'Binh Duong',
  ),
  47 => 
  array (
    'id' => 75,
    'name' => 'Đồng Nai',
    'slug' => 'dong-nai',
    'type' => 'Tỉnh',
    'lat' => '11.0355624',
    'lon' => '107.1881076',
    'region' => 'Đông Nam Bộ',
    'search_name' => 'Dong Nai',
  ),
  48 => 
  array (
    'id' => 77,
    'name' => 'Bà Rịa - Vũng Tàu',
    'slug' => 'ba-ria-vung-tau',
    'type' => 'Tỉnh',
    'lat' => '10.5738801',
    'lon' => '107.3284362',
    'region' => 'Đông Nam Bộ',
    'search_name' => 'Vung Tau',
  ),
  49 => 
  array (
    'id' => 79,
    'name' => 'Hồ Chí Minh',
    'slug' => 'ho-chi-minh',
    'type' => 'Trung ương',
    'lat' => '10.7763897',
    'lon' => '106.7011391',
    'region' => 'Đông Nam Bộ',
    'search_name' => 'Ho Chi Minh City',
  ),
  50 => 
  array (
    'id' => 80,
    'name' => 'Long An',
    'slug' => 'long-an',
    'type' => 'Tỉnh',
    'lat' => '10.6983968',
    'lon' => '106.1883517',
    'region' => 'Đồng bằng sông Cửu Long',
    'search_name' => 'An Long',
  ),
  51 => 
  array (
    'id' => 82,
    'name' => 'Tiền Giang',
    'slug' => 'tien-giang',
    'type' => 'Tỉnh',
    'lat' => '10.4030368',
    'lon' => '106.361633',
    'region' => 'Đồng bằng sông Cửu Long',
    'search_name' => 'My Tho',
  ),
  52 => 
  array (
    'id' => 83,
    'name' => 'Bến Tre',
    'slug' => 'ben-tre',
    'type' => 'Tỉnh',
    'lat' => '10.1093637',
    'lon' => '106.4811559',
    'region' => 'Đồng bằng sông Cửu Long',
    'search_name' => 'Ben Tre',
  ),
  53 => 
  array (
    'id' => 84,
    'name' => 'Trà Vinh',
    'slug' => 'tra-vinh',
    'type' => 'Tỉnh',
    'lat' => '9.8037998',
    'lon' => '106.3256808',
    'region' => 'Đồng bằng sông Cửu Long',
    'search_name' => 'Tra Vinh',
  ),
  54 => 
  array (
    'id' => 86,
    'name' => 'Vĩnh Long',
    'slug' => 'vinh-long',
    'type' => 'Tỉnh',
    'lat' => '10.1203043',
    'lon' => '106.0125705',
    'region' => 'Đồng bằng sông Cửu Long',
    'search_name' => 'Vinh Long',
  ),
  55 => 
  array (
    'id' => 87,
    'name' => 'Đồng Tháp',
    'slug' => 'dong-thap',
    'type' => 'Tỉnh',
    'lat' => '10.590424',
    'lon' => '105.6802341',
    'region' => 'Đồng bằng sông Cửu Long',
    'search_name' => 'Dong Thap',
  ),
  56 => 
  array (
    'id' => 89,
    'name' => 'An Giang',
    'slug' => 'an-giang',
    'type' => 'Tỉnh',
    'lat' => '10.5392057',
    'lon' => '105.2312822',
    'region' => 'Đồng bằng sông Cửu Long',
    'search_name' => 'An Giang',
  ),
  57 => 
  array (
    'id' => 91,
    'name' => 'Kiên Giang',
    'slug' => 'kien-giang',
    'type' => 'Tỉnh',
    'lat' => '9.9904962',
    'lon' => '105.2435248',
    'region' => 'Đồng bằng sông Cửu Long',
    'search_name' => 'Rach Gia',
  ),
  58 => 
  array (
    'id' => 92,
    'name' => 'Cần Thơ',
    'slug' => 'can-tho',
    'type' => 'Trung ương',
    'lat' => '10.0364216',
    'lon' => '105.7875219',
    'region' => 'Đồng bằng sông Cửu Long',
    'search_name' => 'Can Tho',
  ),
  59 => 
  array (
    'id' => 93,
    'name' => 'Hậu Giang',
    'slug' => 'hau-giang',
    'type' => 'Tỉnh',
    'lat' => '9.7985063',
    'lon' => '105.6379524',
    'region' => 'Đồng bằng sông Cửu Long',
    'search_name' => 'Vi Thanh',
  ),
  60 => 
  array (
    'id' => 94,
    'name' => 'Sóc Trăng',
    'slug' => 'soc-trang',
    'type' => 'Tỉnh',
    'lat' => '9.5628369',
    'lon' => '105.9493991',
    'region' => 'Đồng bằng sông Cửu Long',
    'search_name' => 'Soc Trang',
  ),
  61 => 
  array (
    'id' => 95,
    'name' => 'Bạc Liêu',
    'slug' => 'bac-lieu',
    'type' => 'Tỉnh',
    'lat' => '9.3298341',
    'lon' => '105.509946',
    'region' => 'Đồng bằng sông Cửu Long',
    'search_name' => 'Bac Lieu',
  ),
  62 => 
  array (
    'id' => 96,
    'name' => 'Cà Mau',
    'slug' => 'ca-mau',
    'type' => 'Tỉnh',
    'lat' => '9.0180177',
    'lon' => '105.0869724',
    'region' => 'Đồng bằng sông Cửu Long',
    'search_name' => 'Ca Mau',
  ),
);
